name: Update Download Count

on:
  schedule:
    - cron: '0 0 * * *'  # Mỗi ngày lúc 00:00 UTC
  workflow_dispatch:     # Cho phép chạy thủ công từ GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Run script
        run: node scripts/update-download-count.js

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "🔁 update download count" || echo "No changes"
          git push
